### ISSUE TITLE
Different icons in dired and ivy

### ISSUE THREAD

**Issue by srustamo** [jtbm37/all-the-icons-dired#14]
I can't figure out why with all things equal I see different icons in dired buffers and ivy minibuffer for some icons on the screenshot.
<img width="716" alt="screenshot 2018-07-25 12 46 33" src="https://user-images.githubusercontent.com/749813/43187173-33278fc8-900a-11e8-8b11-ca96900ec3c6.png">

**Comment by cnngimenez** [comment]
See [this pull request](https://github.com/domtronn/all-the-icons.el/pull/106) in the all-the-icons package. 

The problem is the font-lock in Emacs 26, it doesn't recognize the `font-lock-ignore` text property anymore.

In the pull request, you can [see the modifications](https://github.com/domtronn/all-the-icons.el/pull/106/files) if you don't want to wait for the package update.

**Comment by srustamo** [comment]
Great. Thanks for heads up!
